deployment:
  tasks:
    - export DEPLOYPATH=/home/vendnuli/deploy/public/
    - /bin/cp -R build/static $DEPLOYPATH
    - /bin/cp -R build/asset-manifest.json $DEPLOYPATH
    - /bin/cp -R build/index.html $DEPLOYPATH
    - /bin/cp -R build/logo.svg $DEPLOYPATH
    - /bin/cp -R build/manifest.json $DEPLOYPATH
    - /bin/cp -R build/robots.txt $DEPLOYPATH