deployment:
  tasks:
    - export DEPLOYPATH=/home/vendnuli/deploy/public/
    - /bin/cp -R server/static $DEPLOYPATH
    - /bin/cp -R server/asset-manifest.json $DEPLOYPATH
    - /bin/cp -R server/index.html $DEPLOYPATH
    - /bin/cp -R server/logo.svg $DEPLOYPATH
    - /bin/cp -R server/manifest.json $DEPLOYPATH
    - /bin/cp -R server/robots.txt $DEPLOYPATH